### ISSUE TITLE
As the only player that is online in the Lobby, I want to play the game alone in order to improve my betting skills. 

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#15]
### Acceptance Criteria:
- [ ] When clicking the Button “Single Player Mode”, the player can decide how many rounds he wants to play. 
- [ ] The same criteria apply for exiting the session as in Leaving Game Session while in a Game. 
- [ ] Chart data is previously fetched and stored in a database. 

### Development Tasks:

- [x] sopra-fs23-group-33/sopra-server#96

**Comment by COrtsJosep** [comment]
# Mein Vorschlag
## Ein Single Player Spiel ist halt... ein Spiel mit nur ein Spieler. Vielleicht können viele Elemente recycelt werden.
- Add a "Single Player Mode" button to the dashboard page. High, 1h.
- Add a form for the player to create a new individual game, with paramters: number of rounds. High, 1h.
- Create game mode where cooperative features (certain events and power-ups) are deactivated or modified, everything else stays the same. High, 8h.

**Comment by stsaxe** [comment]
c90ea8afbfbe640c72e2ccbde8e1b16dc81c9cf1
